baseurl                  = "https://example.com"           # Your domain name
languageCode             = "en-us"
defaultContentLanguage   = "en"
isMultilingual           = false
title                    = "andrew li"
theme                    = "sam"
pygmentsStyle            = "monokai"                        # https://help.farbox.com/pygments.html
pygmentsCodefences       = true
# googleAnalytics        = ""                               # Tracking code, eg. "UA-111111111-1"

[params]
    dateform             = "Mon Jan 02, 2006"
    dateformfull         = "Mon Jan 2 2006 15:04:05 EST"
    favicon              = "sam.ico"
    homepage             = "main"                           # What to call the home page link, link will not be rendered if empty
    footerText           = ""

# Metadata for Open Graph and Twitter
    description          = "Andrew Li's personal website"               # Max 160 characters show in search results
    images               = ["tn.png"]                       # Image that shows on Twitter cards and Open Graph links to the site
    title                = "Call me Sam"
    # rss                = ""

[[params.videoBackground.sources]]
    source  = "/sample_video.mp4"
    type    = "video/mp4"
    poster  = "/background.png"
[params.videoBackground]
    overlay = "rgba(0, 0, 0, 0.4)" # optional

[[params.mainMenu]]
    link = "/about"
    text = "andrew li"

[[params.mainMenu]]
    link = "/publication"
    text = "publication"

[[params.mainMenu]]
    link = "/teach"
    text = "teach"

[[params.mainMenu]]
    link = "/conference"
    text = "conference"

[[params.mainMenu]]
    link = "/contact"
    text = "contact"

[imaging]
    quality = 75
